export enum ApplicationProgressStateEnum {
  PERSONAL_DETAILS,
  CONTACT_DETAILS,
  INCOME_DETAILS,
  CHECKING,
  MOBILE_VERIFICATION,
  EMPLOYMENT_DETAILS,
  INSTANTOR,
  ACCEPTED,
  REJECTED,
  CONTINUE,
}
